[package]
name = "d2fn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
blake3 = "1.4.1"
filewalker = { path = "../filewalker"}
